# SIC

## Ví dụ với sklearn

In [18]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.datasets import load_breast_cancer
from sklearn.model_selection import train_test_split
import matplotlib.pyplot as plt
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score
import numpy as np
import pandas as pd

In [20]:
df = load_breast_cancer()

In [22]:
X, y = df.data, df.target

In [24]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=1234)

In [26]:
model = DecisionTreeClassifier(criterion='entropy')
model.fit(X_train, y_train)

DecisionTreeClassifier(criterion='entropy')

In [28]:
y_pred = model.predict(X_test)

In [30]:
accuracy_score(y_pred, y_test)

0.8947368421052632

In [32]:
y_pred

array([1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0,
       0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 1,
       1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0,
       0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0,
       1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1,
       0, 1, 1, 0])

In [43]:
y_pred_2d = y_pred.reshape(len(y_pred), 1)
y_test_2d = y_test.reshape(len(y_test), 1)

In [45]:
df1 = pd.DataFrame(y_pred_2d)
df2 = pd.DataFrame(y_test_2d)

In [63]:
total_df = df1.join(df2,lsuffix='x', rsuffix='y')

In [67]:
total_df.columns = ['pred', 'real']

In [85]:
total_df[total_df['pred'] == total_df['real']].shape[0] / len(total_df)

0.8947368421052632

In [107]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
X_train

array([[-0.36180827, -0.26521011, -0.31715702, ..., -0.07967528,
        -0.52798733,  0.2506337 ],
       [-0.8632675 ,  0.71560604, -0.85646012, ..., -0.76980239,
         0.44312729, -0.20987332],
       [-0.4334453 ,  0.32513895, -0.41286667, ..., -0.06601541,
        -1.1169427 ,  0.0329492 ],
       ...,
       [-0.479293  , -0.17689018, -0.45697634, ..., -0.20261414,
         0.18670009,  0.17414996],
       [ 1.16835876, -0.15364809,  1.17466524, ...,  0.26789258,
         0.19828067, -0.23394164],
       [-0.40765597, -1.29715887, -0.42826344, ..., -0.78042674,
        -0.88036793, -0.80355834]])

In [91]:
df_scale_previous = pd.DataFrame(df['data'])

In [111]:
df_scale_previous

0      1       2       3        4        5        6        7       8   \
0    17.99  10.38  122.80  1001.0  0.11840  0.27760  0.30010  0.14710  0.2419   
1    20.57  17.77  132.90  1326.0  0.08474  0.07864  0.08690  0.07017  0.1812   
2    19.69  21.25  130.00  1203.0  0.10960  0.15990  0.19740  0.12790  0.2069   
3    11.42  20.38   77.58   386.1  0.14250  0.28390  0.24140  0.10520  0.2597   
4    20.29  14.34  135.10  1297.0  0.10030  0.13280  0.19800  0.10430  0.1809   
..     ...    ...     ...     ...      ...      ...      ...      ...     ...   
564  21.56  22.39  142.00  1479.0  0.11100  0.11590  0.24390  0.13890  0.1726   
565  20.13  28.25  131.20  1261.0  0.09780  0.10340  0.14400  0.09791  0.1752   
566  16.60  28.08  108.30   858.1  0.08455  0.10230  0.09251  0.05302  0.1590   
567  20.60  29.33  140.10  1265.0  0.11780  0.27700  0.35140  0.15200  0.2397   
568   7.76  24.54   47.92   181.0  0.05263  0.04362  0.00000  0.00000  0.1587   

          9   ...      20     21      22      23       24       25      26  \
0    0.07871  ...  25.380  17.33  184.60  2019.0  0.16220  0.66560  0.7119   
1    0.05667  ...  24.990  23.41  158.80  1956.0  0.12380  0.18660  0.2416   
2    0.05999  ...  23.570  25.53  152.50  1709.0  0.14440  0.42450  0.4504   
3    0.09744  ...  14.910  26.50   98.87   567.7  0.20980  0.86630  0.6869   
4    0.05883  ...  22.540  16.67  152.20  1575.0  0.13740  0.20500  0.4000   
..       ...  ...     ...    ...     ...     ...      ...      ...     ...   
564  0.05623  ...  25.450  26.40  166.10  2027.0  0.14100  0.21130  0.4107   
565  0.05533  ...  23.690  38.25  155.00  1731.0  0.11660  0.19220  0.3215   
566  0.05648  ...  18.980  34.12  126.70  1124.0  0.11390  0.30940  0.3403   
567  0.07016  ...  25.740  39.42  184.60  1821.0  0.16500  0.86810  0.9387   
568  0.05884  ...   9.456  30.37   59.16   268.6  0.08996  0.06444  0.0000   

         27      28       29  
0    0.2654  0.4601  0.11890  
1    0.1860  0.2750  0.08902  
2    0.2430  0.3613  0.08758  
3    0.2575  0.6638  0.17300  
4    0.1625  0.2364  0.07678  
..      ...     ...      ...  
564  0.2216  0.2060  0.07115  
565  0.1628  0.2572  0.06637  
566  0.1418  0.2218  0.07820  
567  0.2650  0.4087  0.12400  
568  0.0000  0.2871  0.07039  

[569 rows x 30 columns]

In [113]:
scaler.fit(X_train)

StandardScaler()

In [115]:
X_train = scaler.transform(X_train)

In [117]:
df_scale_after = pd.DataFrame(X_train)

In [121]:
df_scale_after.describe()

0             1             2             3             4   \
count  4.550000e+02  4.550000e+02  4.550000e+02  4.550000e+02  4.550000e+02   
mean  -1.561632e-17 -3.904081e-18 -2.732857e-17 -7.808162e-18  3.123265e-17   
std    1.001101e+00  1.001101e+00  1.001101e+00  1.001101e+00  1.001101e+00   
min   -2.052156e+00 -2.087390e+00 -2.009137e+00 -1.471566e+00 -3.124498e+00   
25%   -6.884731e-01 -7.323761e-01 -6.895924e-01 -6.633696e-01 -7.191167e-01   
50%   -2.299961e-01 -1.094881e-01 -2.276893e-01 -3.142907e-01 -4.937195e-02   
75%    4.620176e-01  5.842882e-01  4.859718e-01  3.647612e-01  6.353352e-01   
max    4.002320e+00  3.358232e+00  4.012665e+00  5.295968e+00  3.435438e+00   

                 5             6             7             8             9   \
count  4.550000e+02  4.550000e+02  4.550000e+02  4.550000e+02  4.550000e+02   
mean  -1.171224e-17 -2.732857e-17  3.904081e-18 -3.513673e-17  9.760202e-18   
std    1.001101e+00  1.001101e+00  1.001101e+00  1.001101e+00  1.001101e+00   
min   -1.625398e+00 -1.120117e+00 -1.265291e+00 -2.785498e+00 -1.838462e+00   
25%   -7.764829e-01 -7.571194e-01 -7.422218e-01 -7.167033e-01 -6.957746e-01   
50%   -1.891111e-01 -3.456142e-01 -3.898874e-01 -8.370009e-02 -1.956251e-01   
75%    5.015768e-01  5.345305e-01  5.977872e-01  5.253118e-01  4.741029e-01   
max    3.961713e+00  4.215761e+00  3.939532e+00  4.522644e+00  4.956129e+00   

       ...          20            21            22            23  \
count  ...  455.000000  4.550000e+02  4.550000e+02  4.550000e+02   
mean   ...    0.000000 -1.952040e-18  2.732857e-17 -7.808162e-18   
std    ...    1.001101  1.001101e+00  1.001101e+00  1.001101e+00   
min    ...   -1.742974 -2.149157e+00 -1.707907e+00 -1.236098e+00   
25%    ...   -0.671351 -7.247685e-01 -6.865852e-01 -6.452266e-01   
50%    ...   -0.273797 -6.198191e-02 -2.932627e-01 -3.459288e-01   
75%    ...    0.469140  6.771256e-01  5.143356e-01  2.809007e-01   
max    ...    3.516014  3.803871e+00  3.646847e+00  4.529314e+00   

                 24            25            26            27            28  \
count  4.550000e+02  4.550000e+02  4.550000e+02  4.550000e+02  4.550000e+02   
mean   5.075305e-17 -3.123265e-17  3.904081e-18 -1.952040e-17 -1.561632e-17   
std    1.001101e+00  1.001101e+00  1.001101e+00  1.001101e+00  1.001101e+00   
min   -2.657705e+00 -1.417530e+00 -1.290001e+00 -1.743144e+00 -2.210481e+00   
25%   -6.814276e-01 -6.711109e-01 -7.534134e-01 -7.637313e-01 -6.305582e-01   
50%   -7.473258e-02 -2.599793e-01 -2.163615e-01 -2.102030e-01 -1.243213e-01   
75%    5.771419e-01  4.941234e-01  5.096232e-01  7.254983e-01  4.538807e-01   
max    3.858028e+00  4.969169e+00  4.529031e+00  2.673548e+00  6.182133e+00   

                 29  
count  4.550000e+02  
mean   1.561632e-17  
std    1.001101e+00  
min   -1.561978e+00  
25%   -6.885653e-01  
50%   -2.221749e-01  
75%    4.177748e-01  
max    6.592366e+00  

[8 rows x 30 columns]

## Tiền xử lí dữ liệu cho ML

In [127]:
from sklearn.datasets import load_iris

iris = load_iris()

In [149]:
df = pd.DataFrame(iris.data)

iris.feature_names

In [153]:
df.columns = iris.feature_names

In [157]:
df.columns

Index(['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)',
       'petal width (cm)'],
      dtype='object')

## One hot encoding

In [160]:
iris.target

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [164]:
iris = pd.DataFrame(iris.target, columns = ['species'])

In [170]:
iris.replace({0:'setosa',1:'versocolor',2:'virginica'}, inplace = True)

In [172]:
iris

species
0       setosa
1       setosa
2       setosa
3       setosa
4       setosa
..         ...
145  virginica
146  virginica
147  virginica
148  virginica
149  virginica

[150 rows x 1 columns]

In [182]:
pd.get_dummies(iris['species'], dtype=int)

setosa  versocolor  virginica
0         1           0          0
1         1           0          0
2         1           0          0
3         1           0          0
4         1           0          0
..      ...         ...        ...
145       0           0          1
146       0           0          1
147       0           0          1
148       0           0          1
149       0           0          1

[150 rows x 3 columns]

In [186]:
from sklearn.preprocessing import OneHotEncoder

enc = OneHotEncoder()
len_iris = len(iris)

In [190]:
iris_2d = np.array(iris['species'])

In [194]:
iris_2d = iris_2d.reshape(len_iris, 1)

In [200]:
iris_2d.shape

(150, 1)

In [204]:
mat = enc.fit_transform(iris_2d)

In [206]:
print(mat)

  (0, 0)	1.0
  (1, 0)	1.0
  (2, 0)	1.0
  (3, 0)	1.0
  (4, 0)	1.0
  (5, 0)	1.0
  (6, 0)	1.0
  (7, 0)	1.0
  (8, 0)	1.0
  (9, 0)	1.0
  (10, 0)	1.0
  (11, 0)	1.0
  (12, 0)	1.0
  (13, 0)	1.0
  (14, 0)	1.0
  (15, 0)	1.0
  (16, 0)	1.0
  (17, 0)	1.0
  (18, 0)	1.0
  (19, 0)	1.0
  (20, 0)	1.0
  (21, 0)	1.0
  (22, 0)	1.0
  (23, 0)	1.0
  (24, 0)	1.0
  :	:
  (125, 2)	1.0
  (126, 2)	1.0
  (127, 2)	1.0
  (128, 2)	1.0
  (129, 2)	1.0
  (130, 2)	1.0
  (131, 2)	1.0
  (132, 2)	1.0
  (133, 2)	1.0
  (134, 2)	1.0
  (135, 2)	1.0
  (136, 2)	1.0
  (137, 2)	1.0
  (138, 2)	1.0
  (139, 2)	1.0
  (140, 2)	1.0
  (141, 2)	1.0
  (142, 2)	1.0
  (143, 2)	1.0
  (144, 2)	1.0
  (145, 2)	1.0
  (146, 2)	1.0
  (147, 2)	1.0
  (148, 2)	1.0
  (149, 2)	1.0
